
export const API = 'http://127.0.0.1:8000';

export const API_CONFIG = {
};

export const ACTIONS = {
  ADD_STRATEGY_TO_INTERFACE: 'ADD_STRATEGY_TO_INTERFACE',
  CLEAR_STRATEGIES_FROM_INTERFACE: 'CLEAR_STRATEGIES_FROM_INTERFACE',
  DRAGGING_STRATEGY: 'DRAGGING_STRATEGY',
  FETCH_GAMES: 'FETCH_GAMES',
  FETCH_MATCHES: 'FETCH_MATCHES',
  FETCH_MORAN_PROCESSES: 'FETCH_MORAN_PROCESSES',
  FETCH_STRATEGIES: 'FETCH_STRATEGIES',
  FETCH_TOURNAMENTS: 'FETCH_TOURNAMENTS',
  INITIALIZE_STRATEGIES: 'INITIALIZE_STRATEGIES',
  REMOVE_STRATEGY_FROM_INTERFACE: 'REMOVE_STRATEGY_FROM_INTERFACE',
  RESET_CONTEST_TYPE: 'RESET_CONTEST_TYPE',
  SELECT_CONTEST_TYPE: 'SELECT_CONTEST_TYPE',
  STORE_GAME_RESULTS: 'STORE_GAME_RESULTS',
  UPDATE_STRATEGY_FILTERS: 'UPDATE_STRATEGY_FILTERS',
  UPDATE_STRATEGY_PARAMETER: 'UPDATE_STRATEGY_PARAMETER',
};

export const ItemTypes = {
  STRATEGY: 'STRATEGY'
};
